"""
Flywheel — LLM-generated preference pairs and transcript quality filtering.

Collects preference pairs generated by the agent pipeline (gold judge and rubric scorer)
and filters transcripts for quality issues before Phase 4 reward model training.

Core components:
  PreferenceStore — SQLite storage for (chosen vs rejected rubric) pairs
  PreferencePair — Dataclass representing a single preference pair
  TranscriptFilter — Detects low-quality transcripts (truncation, encoding issues, etc.)
"""
